services:
  nginx:
    image: nginx:stable
    ports:
      - "80:80"
    volumes:
      - ./nginx/html:/usr/share/nginx/html:ro
      - ./nginx/conf:/etc/nginx:ro
    depends_on:
      - api

  api:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8000"
    environment:
      API_ROOT_PATH: /api
      TODO_DATA_DIR: /data
    volumes:
      - ./data:/data

  dozzle:
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # read docker log
    ports:
      - "8888:8080"
    environment:
      - DOZZLE_LEVEL=info

