events {}

http {
  server {
    listen 80;

    # Nginx serves index.html itself
    location = /index.html {
      root /usr/share/nginx/html;
    }

    # (Optional) make / show index.html
    location = / {
      root /usr/share/nginx/html;
    }

    # Redirect /api -> /api/
    location = /api {
      return 301 /api/;
    }

    # Proxy EVERYTHING under /api/ to the API container
    # /api/...  ->  http://api:8000/...
    location /api/ {
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;

      proxy_pass http://api:8000/;
    }
  }
}
